version: "3"

services: 
  validator1:
    networks:
      sui-network:
        ipv4_address: 10.0.0.11
    image: mysten/sui-tools:sui-v1.29.0-release
    container_name: validator1
    hostname: validator1
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info,sui_core=debug,sui_network=debug,sui_node=debug,narwhal=debug,narwhal-primary::helper=info,jsonrpsee=error
      - RPC_WORKER_THREAD=12
      - NEW_CHECKPOINT_WARNING_TIMEOUT_MS=30000
      - NEW_CHECKPOINT_PANIC_TIMEOUT_MS=60000
    volumes:
      - ./genesis/files/validator1-8080.yaml:/opt/sui/config/validator.yaml:ro
      - ./genesis/files/genesis.blob:/opt/sui/config/genesis.blob:ro
      - /tmp/sui/db1:/opt/sui/db:rw
    command:
      [
        "/usr/local/bin/sui-node",
        "--config-path",
        "/opt/sui/config/validator.yaml",
      ]
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"
    ports:
      - "9000:9000"
  validator2:
    networks:
      sui-network:
        ipv4_address: 10.0.0.12
    image: mysten/sui-node:sui-v1.29.0-release
    container_name: validator2
    hostname: validator2
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info,sui_core=debug,sui_network=debug,sui_node=debug,narwhal=debug,narwhal-primary::helper=info,jsonrpsee=error
      - RPC_WORKER_THREAD=12
      - NEW_CHECKPOINT_WARNING_TIMEOUT_MS=30000
      - NEW_CHECKPOINT_PANIC_TIMEOUT_MS=60000
    volumes:
      - ./genesis/files/validator2-8080.yaml:/opt/sui/config/validator.yaml:ro
      - ./genesis/files/genesis.blob:/opt/sui/config/genesis.blob:ro
      - /tmp/sui/db2:/opt/sui/db:rw
    command:
      [
        "/usr/local/bin/sui-node",
        "--config-path",
        "/opt/sui/config/validator.yaml",
      ]
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"
  validator3:
    networks:
      sui-network:
        ipv4_address: 10.0.0.13
    image: mysten/sui-node:sui-v1.29.0-release
    container_name: validator3
    hostname: validator3
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info,sui_core=debug,sui_network=debug,sui_node=debug,narwhal=debug,narwhal-primary::helper=info,jsonrpsee=error
      - RPC_WORKER_THREAD=12
      - NEW_CHECKPOINT_WARNING_TIMEOUT_MS=30000
      - NEW_CHECKPOINT_PANIC_TIMEOUT_MS=60000
    volumes:
      - ./genesis/files/validator3-8080.yaml:/opt/sui/config/validator.yaml:ro
      - ./genesis/files/genesis.blob:/opt/sui/config/genesis.blob:ro
      - /tmp/sui/db3:/opt/sui/db:rw
    command:
      [
        "/usr/local/bin/sui-node",
        "--config-path",
        "/opt/sui/config/validator.yaml",
      ]
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"
  validator4:
    networks:
      sui-network:
        ipv4_address: 10.0.0.14
    image: mysten/sui-node:sui-v1.29.0-release
    container_name: validator4
    hostname: validator4
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info,sui_core=debug,sui_network=debug,sui_node=debug,narwhal=debug,narwhal-primary::helper=info,jsonrpsee=error
      - RPC_WORKER_THREAD=12
      - NEW_CHECKPOINT_WARNING_TIMEOUT_MS=30000
      - NEW_CHECKPOINT_PANIC_TIMEOUT_MS=60000
    volumes:
      - ./genesis/files/validator4-8080.yaml:/opt/sui/config/validator.yaml:ro
      - ./genesis/files/genesis.blob:/opt/sui/config/genesis.blob:ro
      - /tmp/sui/db4:/opt/sui/db:rw
    command:
      [
        "/usr/local/bin/sui-node",
        "--config-path",
        "/opt/sui/config/validator.yaml",
      ]
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"
  fullnode1:
    networks:
      sui-network:
        ipv4_address: 10.0.0.15
    image: mysten/sui-node:sui-v1.29.0-release
    hostname: fullnode1
    container_name: fullnode1
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info,sui_core=debug,sui_network=debug,sui_node=debug,narwhal=debug,narwhal-primary::helper=info,jsonrpsee=error
      - RPC_WORKER_THREAD=12
      - NEW_CHECKPOINT_WARNING_TIMEOUT_MS=30000
      - NEW_CHECKPOINT_PANIC_TIMEOUT_MS=60000
    volumes:
      - ./genesis/static/fullnode.yaml:/opt/sui/config/fullnode.yaml:ro
      - ./genesis/files/genesis.blob:/opt/sui/config/genesis.blob:ro
      - /tmp/sui/db5:/opt/sui/db:rw
    command:
      [
        "/usr/local/bin/sui-node",
        "--config-path",
        "/opt/sui/config/fullnode.yaml",
      ]
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"
  faucet:
    networks:
      sui-network:
        ipv4_address: 10.0.0.18
    image: mysten/sui-tools:sui-v1.29.0-release
    container_name: faucet
    hostname: faucet
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info,sui_core=debug,sui_network=debug,sui_node=debug,narwhal=debug,narwhal-primary::helper=info,jsonrpsee=error
      - RPC_WORKER_THREAD=12
      - NEW_CHECKPOINT_WARNING_TIMEOUT_MS=30000
      - NEW_CHECKPOINT_PANIC_TIMEOUT_MS=60000
    volumes:
      - ./genesis/static/client.yaml:/root/.sui/sui_config/client.yaml:ro
      - ./genesis/static/sui.keystore:/root/.sui/sui_config/sui.keystore:ro
      # - ./genesis/files/genesis.blob:/opt/sui/config/genesis.blob:ro
    command:
      [
        "/usr/local/bin/sui-faucet",
        "--host-ip",
        "0.0.0.0",
        "--write-ahead-log",
        "./faucet.log"
      ]
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"
    ports:
      - "5003:5003"
networks:
  sui-network:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.0.0/24
